### ISSUE TITLE
Integration of the new modules of data augmentation with the pipeline

### ISSUE THREAD

**Issue by farinamhz** [fani-lab/LADy#28]
In this step,
We will add the modules of Back-translation, Word-alignment, and Similarity-comparison to the pipeline to use them for augmenting the data, determine which language is better, which reviews should be added to the original English dataset, and also find the related aspect labels of each augmented or new review.

Edit: In this step, we will add the back-translated reviews to the original dataset and retrain the model.

**Comment by hosseinfani** [comment]
@farinamhz 
I'm closing this issue as it's done already. Let me know otherwise.
