### ISSUE TITLE
Labeling the aspects for back-translated reviews

### ISSUE THREAD

**Issue by farinamhz** [fani-lab/LADy#29]
By using the word alignments and similarity comparison between the original and back-translated reviews, we want to find the new aspect labels for the new (back-translated) reviews.
1. We discard the new reviews which have a similarity score below a threshold with the original reviews (the threshold is 0.5 for now)
2. We add the labels which are aligned with the original labels as the labels of similar-semantic new reviews.

**Comment by hosseinfani** [comment]
@farinamhz 
I'm closing this issue as it's solved now in the pipeline. Let me know otherwise.
