### ISSUE TITLE
Evaluating results of translation

### ISSUE THREAD

**Issue by farinamhz** [fani-lab/LADy#33]
Hi @Lillliant,

We have implemented and got the results of back-translation on two datasets so far, the first one is Semeval-Restaurant-2016, and the other one is Semeval-Restaurant-2015.

Now we want to evaluate the translation and back-translation results based on specific metrics used in this area.
These are some examples of metrics that are more important: exact match, rouge, and bleu. However, you can search and let me know if any other metrics have been used more lately.

You can find the results of the back-translation for
Semeval-2016 in: [``data/augmentation/back-translation``](../tree/main/data/augmentation/back-translation)
and Semeval-2015 in [``output/augmentation/back-translation-Semeval-15``](../tree/main/output/augmentation/back-translation-Semeval-15)

D represents the original dataset in English, D.L represents the translated dataset, and D_L represents the back-translated dataset.
Now we compare D with D.L, then D.L with D_L, and finally D with D_L to find the values for those metrics.

All the texts or reviews you want to compare, whether in original, translated, or back-translated datasets, can be found in the column "sentences".

Please find the values for metrics in these two datasets for these languages: L in {fra, arb, due, spa, and zho}, which are French, Arabic, German, Spanish, and Chinese.

Feel free to let me know if you have any concerns or questions about this task.

@hosseinfani

**Comment by hosseinfani** [comment]
@farinamhz @Lillliant 
I think we can close this issue. Let me know otherwise.
